name: "Upgrade Helm release"
description: "Upgrade Helm release"
inputs:
  azure-client-id:
    description: ""
    required: true
  azure-tenant-id:
    description: ""
    required: true
  azure-subscription-id:
    description: ""
    required: true
permissions:  
  id-token: write
  contents: read
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}
    - uses: azure/setup-kubectl@v3
    - uses: azure/use-kubelogin@v1
    - uses: azure/aks-set-context@v3
      with:
        resource-group: regels.overheid.nl
        cluster-name: regels
        admin: false
        use-kubelogin: true
    - run: kubectl get pods --namespace app 


