name: "Upgrade Helm release"
description: "Upgrade Helm release"
inputs:
  azure-client-id:
    description: ""
    required: true
  azure-tenant-id:
    description: ""
    required: true
  azure-subscription-id:
    description: ""
    required: true
  github-token:
    description: ""
    required: true
  tag:
    default: next
    description: ""
    required: true
  release-name:
    default: docs
    description: ""
    required: true
permissions:
  id-token: write
  contents: read
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}
    - uses: azure/setup-kubectl@v3
    - uses: azure/use-kubelogin@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - uses: azure/aks-set-context@v3
      with:
        resource-group: regels.overheid.nl
        cluster-name: regels
        admin: false
        use-kubelogin: true
    - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      shell: sh
    - run: helm repo add regels-overheid-nl https://minbzk.github.io/helm.regels.overheid.nl/
      shell: sh
    - run: helm upgrade --install --atomic --wait ${{ inputs.release-name }} regels-overheid-nl/${{ inputs.release-name }} --namespace app --set image.tag=${{ inputs.tag }}
      shell: sh
