name: Reusable Workflow
on: 
  workflow_call:
    secrets:
      DATABASE_URL:
        required: true
jobs:
  perform-task:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set-output
        run: | 
          echo "MY_ENV_VAR=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "my-output=${{ secrets.DATABASE_URL }}" >> $GITHUB_OUTPUT
    outputs:
      my-output: ${{ steps.perform-task.outputs.my-output }}