name: Build and push a Docker image to the registry
on:   
  workflow_dispatch:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:  
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - id: set-build-args
        run: ./.github/workflows/build-args/web.yml
      # Use the environment variable
      - run: echo ${{ steps.set-build-args.outputs.set-build-args.build-args }}
      # - uses: ./.github/actions/build-and-push-docker
      #   with:
      #     app: web
      #     tag: next
      #     acr-login-server: ${{ secrets.ACR_LOGIN_SERVER }}
      #     acr-username: ${{ secrets.ACR_USERNAME }}
      #     acr-password: ${{ secrets.ACR_PASSWORD }}
        # with: 
        #   azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #   azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #   azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
