name: Build and push a Docker image to the registry
on:   
  workflow_dispatch:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:  
  id-token: write
  contents: read
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-args-web
    secrets: inherit
  deploy:
    # needs: call-workflow-passing-data
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: "echo Environment Variable: $MY_ENV_VAR"
      # - run: "echo Output: ${{ .use-reusable.outputs.my-output }}"
      # - uses: ./.github/actions/build-and-push-docker
      #   with:
      #     app: web
      #     tag: next
      #     acr-login-server: ${{ secrets.ACR_LOGIN_SERVER }}
      #     acr-username: ${{ secrets.ACR_USERNAME }}
      #     acr-password: ${{ secrets.ACR_PASSWORD }}
        # with: 
        #   azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #   azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #   azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
