name: Build and push a Docker image to the registry
on:   
  workflow_dispatch:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:  
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - id: build-args
        run: |
          # Read the JSON file, encode it as a single-line string, and set it as an environment variable
          BUILD_ARGS=$(jq -c '.' ./.github/configs/production/build-args/web.json)
          echo "BUILD_ARGS=$BUILD_ARGS" >> $GITHUB_ENV

      # Use the environment variable
      - run: echo ${{ toJson(fromJson(env.BUILD_ARGS)) }}
      # - uses: ./.github/actions/build-and-push-docker
      #   with:
      #     app: web
      #     tag: next
      #     acr-login-server: ${{ secrets.ACR_LOGIN_SERVER }}
      #     acr-username: ${{ secrets.ACR_USERNAME }}
      #     acr-password: ${{ secrets.ACR_PASSWORD }}
        # with: 
        #   azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #   azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #   azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
