name: Build and push a Docker image to the registry
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
      version:
        description: 'Version to deploy'
        required: true
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: ./.github/actions/build-and-push-docker
        with: 
          tag: ${{ github.event.inputs.version }}
          app: ${{ github.event.inputs.app }}
          acr-login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          acr-username: ${{ secrets.ACR_USERNAME }}
          acr-password: ${{ secrets.ACR_PASSWORD }}
