name: Changesets Gateway
on:
  workflow_call:
    inputs: 
      package:
        type: string
        required: true
jobs:
  build-args:
    runs-on: ubuntu-latest
    steps: 
      - uses: ./.github/actions/upgrade-helm
