name: Changesets - Gateway
on: 
  workflow_call:
    inputs: 
      packages: 
        type: string
        required: true
jobs:
  release-cms:
    if: ${{ fromJson(inputs.packages) |  }}
    uses: ./.github/workflows/build-push-deploy-cms.yml
    secrets: inherit
    with: 
      version: ${{ inputs.version }}
