name: "Docker: Build and Push"
on:
  workflow_call:
    inputs: 
      app:
        type: string
        required: true
      tag: 
        type: string
        required: true
      build-args: 
        type: string
        required: true
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          target: prod
          file: apps/${{ inputs.app }}/Dockerfile
          push: true
          tags: regels.azurecr.io/${{ inputs.app }}:${{ inputs.tag }},regels.azurecr.io/${{ inputs.app }}:latest
          build-args: ${{ inputs.build-args }}
          cache-from: type=registry,ref=regels.azurecr.io/${{ inputs.app }}:buildcache
          cache-to: type=registry,ref=regels.azurecr.io/${{ inputs.app }}:buildcache,mode=max