name: "web: Build, Push and Deploy"
on: 
  workflow_call:
    inputs: 
      version:
        required: true
        description: ''
        type: string
        default: ${{ secrets.github }}
jobs:
  build-push:
    uses: ./.github/workflows/docker-build-push.yml
    with: 
      tag: ${{ inputs.version }}
      build-args: "FOO=${{ inputs.version }}"
  push: 
    runs-on: ubuntu-latest
    steps:
      - run: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/workflows/docker-build-push.yml
        with: 
          foo: ${{ secrets.GITHUB_TOKEN }}