name: X
on: 
  workflow_call:
    inputs:
      target:
        required: true
        type: string
jobs:
  perform-task:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set-output
        run: | 
          echo "MY_ENV_VAR=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "my-output=${{ secrets.DATABASE_URL }}" >> $GITHUB_OUTPUT
    outputs:
      my-output: ${{ steps.set-output.outputs.my-output }}